### PR TITLE
Origin/encode rr a and aaaa

### PR DESCRIPTION
**Pull request by Shailesh-Venugopal**
Add capability to encode A and AAAA resource records

### CODE REVIEW

**Comment by spc476** [comment]
Re: adding casts---normal C compilers shouldn't be complaining about those lines.  Do you perhaps have the warnings cranked up high?  Or using a C++ compiler?

**Comment by spc476** [comment]
The issue I have with the A and AAAA encoding routines is you don't do the DNS compression for domain labels.  What you have _will_  work, but can lead to larger than expected DNS packets on the receiving end.  That's why I haven't added such code---I still haven't come up with a good way of dealing with that that also avoids calling malloc()/realloc() (a goal of my library).

**Comment by Shailesh-Venugopal** [comment]
@spc476 Correct, I have both :) warnings cranked up to the max and a C++ compiler

**Comment by Shailesh-Venugopal** [comment]
@spc476 Understood, and agreed this is a limitation

**Comment by spc476** [comment]
I just tried compiling the code with clang (I typically use the GCC frontend) and -Weverything and ... wow ... lots of noise there (WARNING:  padding being added!  WARNING:  No padding being added!).  GCC seems to have a better balance here.

**Comment by Shailesh-Venugopal** [comment]
@spc476 I use clang with insane warning levels turned max and then toning down only certain warnings - so my default is '-Wall -Wextra -Weverything' then toned down with '-Wno-padded -Wno-undef -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-covered-switch-default'. So yes, this causes quite some pain, but has helped me track down some odd behavior in the past, and hence I use these as the default.

**Comment by spc476** [comment]
The new version just released now supports encoding and decoding of A and AAAA RR (as well as others) with proper DNS compression.

**Pull request closed without merging**
